server:
  port: ${SERVER_PORT}
  servlet:
    context-path: '/healthforall/'  
spring:
  application:
    name: healthforall
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRE_URL}/HealthInsurance
    username: ${POSTGRE_USERNAME}
    password: ${POSTGRE_PASSWORD}
      
  jpa:
    show-sql: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: update 
            
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html      
  
openapi:
  server:
    url: ${OPEN_API_SERVER_URL}

healthforall:
  security:
    username: healthforall
    password: '01303c3d-398a-42b3-b78d-fc6ec5dd1421'

api:
 security:
  tocken: 
    secret: ${JWT_SECRET:my-secret-key}           
 authorization:
  header: ${AUTHORIZATION_HEADER}
  generates:
    expiration:
      hours: ${GENERATES_EXPIRATION_HOURS}           
#Configuração para windows terminal padrao de cores            
  output:
    ansi:
      enabled: always
                